# -*- coding: utf-8 -*-
"""stockpredictor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v7nfEYT0QWL8TxAIni4VWvSxbSCXZBPl
"""

#Libraries
import pandas as pd
import xgboost as ai
import matplotlib.pyplot as plt
import datetime as time
import yfinance as yf
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

def SKLinReg(data):

  # Split the data into training and testing sets
  features= ['Open','Volume','High','Low']
  target = ['Close']
  traindata = data.iloc[:int(.90*len(data)),:]
  test = data.iloc[int(.90*len(data)):,:]

  # Create a linear regression model
  model = LinearRegression()

  # Fit the model to the training data
  model.fit(traindata[features], traindata['Close'])

  # Evaluate the model on the testing data
  score = model.score(test[features],  test['Close'])
  print('this model score is(sklearn) ',score)
  # Make predictions using the model
  pred = model.predict(test[features])
  return pred , score

def xgbpriceclose(data):
  features= ['Open','Volume','High','Low']
  traindata = data.iloc[:int(.90*len(data)),:]
  #data to test the model
  test = data.iloc[int(.90*len(data)):,:]
  model = ai.XGBRegressor()
  model.fit(traindata[features],traindata['Close'])
  predictions = model.predict(test[features])
  a=model.score(test[features],test['Close'])

  return predictions, a


def XgbSupLearn(data, days):
  #make model and set data so previous close price is input to find the next one
  model = ai.XGBRegressor()
  inputdata = data['Close'].shift(1)
  targetdata = data['Close']
  model.fit(inputdata, targetdata)
  pred = model.predict(inputdata.values[int(.90*len(data)):])
  future = list()
  score=model.score(inputdata,targetdata)

  for n in range(days):
      inputdata = data['Close'].shift(1)
      nextday = model.predict(inputdata[-1:])
      newday = inputdata.index[-1] + pd.Timedelta(days=1)
      newp = pd.DataFrame({'Date': [newday], 'Close': nextday})
      newp.set_index('Date', inplace=True)
      data = pd.concat([data,newp])
      future.append(newp)
      data

  return pred,score,future
  #data grab
def stockdata(ticker,period):
  tickers = yf.Ticker(ticker)
  data = tickers.history(period=period)
  return data

ticker = 'mcd'
period = '1y'
data = stockdata(ticker,period)
XgbP ,a = xgbpriceclose(data)
SKLinRegP, ska = SKLinReg(data)
Sup,score,pred = XgbSupLearn(data,15)

scores = [a ,ska , score]
#plotting data
XgbSupervised_data = Sup.tolist()
SKLinReg = SKLinRegP.tolist()
XgbData = XgbP.tolist()



#plotting block
test = data.iloc[int(.90*len(data)):,:]
plt.plot(data['Close'], label = 'close')
plt.plot(test['Close'].index,XgbP)
plt.plot(test['Close'].index,SKLinRegP)
plt.plot(test['Close'].index,Sup)